// Auto-generated by tools/gen_selftest_vectors.py -- DO NOT EDIT BY HAND.
//
// Expected on-device self-test results, computed with the desktop
// TensorFlow reference frontend and the frozen V2.3 INT8 model.
//   model sha256 : b9554c054bc9a57a00e874824e5a4ab9c3254b4505ca8a3ec67835d193103de0
//   generated    : 2026-09-09T16:36:30Z

#ifndef IRA_SELFTEST_DATA_H_
#define IRA_SELFTEST_DATA_H_

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define IRA_SELFTEST_SAMPLES 16000
#define IRA_SELFTEST_FEATURES 1960  // 49 * 40

// Deterministic LCG used by vector A. Mirrors the Python generator:
//   state = state * 1664525 + 1013904223   (uint32 wraparound)
//   sample = (int16_t)((state >> 16) & 0xFFFF)
#define IRA_SELFTEST_LCG_SEED 0x12345678u
#define IRA_SELFTEST_LCG_A 1664525u
#define IRA_SELFTEST_LCG_C 1013904223u

// Fills pcm[] with vector A. No waveform is stored in flash.
void ira_selftest_fill_lcg(int16_t pcm[IRA_SELFTEST_SAMPLES]);

// ---- vector 'lcg' ----
extern const int8_t ira_selftest_lcg_features[IRA_SELFTEST_FEATURES];
#define IRA_SELFTEST_LCG_Q_OUT (-126)
#define IRA_SELFTEST_LCG_DETECTED 0

// ---- vector 'speech' ----
extern const int8_t ira_selftest_speech_features[IRA_SELFTEST_FEATURES];
#define IRA_SELFTEST_SPEECH_Q_OUT (114)
#define IRA_SELFTEST_SPEECH_DETECTED 1

extern const int16_t ira_selftest_speech_pcm[IRA_SELFTEST_SAMPLES];

#ifdef __cplusplus
}  // extern "C"
#endif

#endif  // IRA_SELFTEST_DATA_H_
