// Auto-generated by tools/convert_tflite_to_c.py -- DO NOT EDIT BY HAND.
//
// Frozen IRA V2.3 INT8 wake-word model.
//   source : cnn/models/ira_cnn_v2_3_int8.tflite
//   sha256 : b9554c054bc9a57a00e874824e5a4ab9c3254b4505ca8a3ec67835d193103de0
//   bytes  : 13312
//
// Regenerate with:  python tools/convert_tflite_to_c.py

#ifndef IRA_MODEL_DATA_H_
#define IRA_MODEL_DATA_H_

#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char ira_model_data[];
extern const unsigned int ira_model_data_len;

// SHA-256 of the embedded model, as a lowercase hex string (65 bytes incl. NUL).
extern const char ira_model_data_sha256[];

#ifdef __cplusplus
}  // extern "C"
#endif

#endif  // IRA_MODEL_DATA_H_
