# -*- coding: utf-8 -*-
"""
Reproducibly convert the frozen IRA V2.3 INT8 .tflite model into C/C++ source
for embedding on ESP32-S3.

The .tflite file is opened READ-ONLY and never modified.

Outputs:
    esp32/main/ira_model_data.h
    esp32/main/ira_model_data.cc

Usage:
    python tools/convert_tflite_to_c.py
    python tools/convert_tflite_to_c.py --check      # verify without rewriting
"""
import argparse
import hashlib
import sys
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
SRC = REPO / "cnn" / "models" / "ira_cnn_v2_3_int8.tflite"
OUT_DIR = REPO / "esp32" / "main"
OUT_H = OUT_DIR / "ira_model_data.h"
OUT_CC = OUT_DIR / "ira_model_data.cc"

EXPECT_SHA = "b9554c054bc9a57a00e874824e5a4ab9c3254b4505ca8a3ec67835d193103de0"
EXPECT_BYTES = 13312

BYTES_PER_LINE = 12
ALIGNMENT = 16          # TFLite Micro requires >=8; 16 is safe on ESP32-S3


def sha256_bytes(b):
    return hashlib.sha256(b).hexdigest()


def make_header():
    return f"""// Auto-generated by tools/convert_tflite_to_c.py -- DO NOT EDIT BY HAND.
//
// Frozen IRA V2.3 INT8 wake-word model.
//   source : cnn/models/ira_cnn_v2_3_int8.tflite
//   sha256 : {EXPECT_SHA}
//   bytes  : {EXPECT_BYTES}
//
// Regenerate with:  python tools/convert_tflite_to_c.py

#ifndef IRA_MODEL_DATA_H_
#define IRA_MODEL_DATA_H_

#ifdef __cplusplus
extern "C" {{
#endif

extern const unsigned char ira_model_data[];
extern const unsigned int ira_model_data_len;

// SHA-256 of the embedded model, as a lowercase hex string (65 bytes incl. NUL).
extern const char ira_model_data_sha256[];

#ifdef __cplusplus
}}  // extern "C"
#endif

#endif  // IRA_MODEL_DATA_H_
"""


def make_source(blob, digest):
    lines = []
    a = lines.append
    a("// Auto-generated by tools/convert_tflite_to_c.py -- DO NOT EDIT BY HAND.")
    a("//")
    a("// Frozen IRA V2.3 INT8 wake-word model, embedded as a byte array.")
    a(f"//   source : cnn/models/ira_cnn_v2_3_int8.tflite")
    a(f"//   sha256 : {digest}")
    a(f"//   bytes  : {len(blob)}")
    a(f"//   generated (UTC): {datetime.now(timezone.utc).strftime('%Y-%m-%dT%H:%M:%SZ')}")
    a("//")
    a("// The array is 16-byte aligned: TensorFlow Lite Micro requires the model")
    a("// flatbuffer to be at least 8-byte aligned or GetModel() will fault.")
    a("")
    a('#include "ira_model_data.h"')
    a("")
    a("#if defined(__has_attribute)")
    a("#if __has_attribute(aligned)")
    a(f"#define IRA_MODEL_ALIGN __attribute__((aligned({ALIGNMENT})))")
    a("#endif")
    a("#endif")
    a("#ifndef IRA_MODEL_ALIGN")
    a(f"#define IRA_MODEL_ALIGN alignas({ALIGNMENT})")
    a("#endif")
    a("")
    a("const unsigned char ira_model_data[] IRA_MODEL_ALIGN = {")
    for i in range(0, len(blob), BYTES_PER_LINE):
        chunk = blob[i:i + BYTES_PER_LINE]
        a("    " + " ".join(f"0x{b:02x}," for b in chunk))
    a("};")
    a("")
    a(f"const unsigned int ira_model_data_len = {len(blob)};")
    a("")
    a(f'const char ira_model_data_sha256[] = "{digest}";')
    a("")
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="verify the model and existing outputs without rewriting")
    args = ap.parse_args()

    print("=" * 74)
    print("TFLITE -> C ARRAY CONVERTER (frozen IRA V2.3 INT8)")
    print("=" * 74)
    print(f"  source path : {SRC}")

    if not SRC.exists():
        print("  ERROR: source model not found.")
        return 2

    blob = SRC.read_bytes()
    digest = sha256_bytes(blob)
    print(f"  model size  : {len(blob)} bytes")
    print(f"  sha256      : {digest}")

    ok = True
    if len(blob) != EXPECT_BYTES:
        print(f"  ERROR: size mismatch, expected {EXPECT_BYTES}")
        ok = False
    if digest != EXPECT_SHA:
        print(f"  ERROR: sha256 mismatch, expected {EXPECT_SHA}")
        ok = False
    if not ok:
        print("\n  STOP: the model is not the frozen artifact. Nothing written.")
        return 2
    print("  integrity   : SHA256 and size MATCH the frozen model")

    header = make_header()
    source = make_source(blob, digest)

    if args.check:
        same = (OUT_H.exists() and OUT_H.read_text(encoding="utf-8") == header
                and OUT_CC.exists()
                # ignore the generated-at line when comparing
                and [l for l in OUT_CC.read_text(encoding="utf-8").splitlines()
                     if "generated (UTC)" not in l]
                == [l for l in source.splitlines() if "generated (UTC)" not in l])
        print(f"\n  --check: outputs are {'UP TO DATE' if same else 'STALE or MISSING'}")
        return 0 if same else 1

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_H.write_text(header, encoding="utf-8")
    OUT_CC.write_text(source, encoding="utf-8")

    print("\n  output files:")
    print(f"    {OUT_H}   ({OUT_H.stat().st_size} bytes)")
    print(f"    {OUT_CC}  ({OUT_CC.stat().st_size} bytes)")
    print(f"\n  array symbol      : ira_model_data[]")
    print(f"  array length      : ira_model_data_len = {len(blob)}")
    print(f"  alignment         : {ALIGNMENT} bytes")
    print(f"  source .tflite    : NOT modified")

    # round-trip check: parse the emitted array back out and compare
    emitted = []
    for line in OUT_CC.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        if s.startswith("0x"):
            emitted += [int(t.strip().rstrip(","), 16) for t in s.split() if t.strip(",")]
    rt = bytes(emitted)
    print(f"\n  round-trip verify : {len(rt)} bytes, sha256 {sha256_bytes(rt)}")
    if rt == blob:
        print("  ROUND-TRIP OK: emitted array is byte-identical to the .tflite")
    else:
        print("  ERROR: round-trip mismatch")
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
