# -*- coding: utf-8 -*-
"""
Generate the on-device self-test reference for ESP32-S3.

Produces esp32/main/ira_selftest_data.h / .cc containing:
  - the EXPECTED 49x40 INT8 features
  - the EXPECTED q_out and detection decision
for deterministic test vectors, computed with the SAME desktop reference the
parity harness uses (TensorFlow frontend + frozen V2.3 INT8 model).

Vector A "lcg"  : compact deterministic LCG-generated PCM. Reproduced on device
                  by the identical LCG in C -- no waveform is stored.
Vector B "speech": one real 16000-sample window from a development recording,
                   stored as PCM16 so the self-test exercises a real DETECTION.
                   Read-only; the recording is not modified or trained on.

Nothing is retrained, re-quantized, or re-thresholded.
"""
import hashlib
import os
from datetime import datetime, timezone
from pathlib import Path

import numpy as np

os.environ.setdefault("TF_CPP_MIN_LOG_LEVEL", "2")
import tensorflow as tf

REPO = Path(__file__).resolve().parent.parent
TFLITE = REPO / "cnn" / "models" / "ira_cnn_v2_3_int8.tflite"
WAV_DIR = REPO / "dataset" / "new data set"
OUT_H = REPO / "esp32" / "main" / "ira_selftest_data.h"
OUT_CC = REPO / "esp32" / "main" / "ira_selftest_data.cc"

EXPECT_SHA = "b9554c054bc9a57a00e874824e5a4ab9c3254b4505ca8a3ec67835d193103de0"
N, FRAMES, BINS = 16000, 49, 40
IN_SCALE, IN_ZP = 0.06078097224235535, 49
Q_MIN = -25

# --- LCG (Numerical Recipes). Must match ira_selftest_lcg() in C exactly. ---
LCG_SEED = 0x12345678
LCG_A, LCG_C = 1664525, 1013904223


def lcg_pcm(n=N, seed=LCG_SEED):
    out = np.empty(n, dtype=np.int16)
    s = np.uint32(seed)
    for i in range(n):
        s = np.uint32((np.uint64(s) * LCG_A + LCG_C) & 0xFFFFFFFF)
        out[i] = np.int16(np.uint16((int(s) >> 16) & 0xFFFF))
    return out


def py_features_int8(pcm):
    x = (pcm.astype(np.float32) / 32768.0)
    s = tf.signal.stft(tf.constant(x), frame_length=480, frame_step=320,
                       fft_length=512, pad_end=False)
    lg = tf.math.log(tf.abs(s) + 1e-6)[:, :BINS]
    m = tf.reduce_mean(lg)
    d = tf.math.reduce_std(lg) + 1e-6
    f = ((lg - m) / d).numpy().astype(np.float32)
    return np.clip(np.round(f / IN_SCALE + IN_ZP), -128, 127).astype(np.int8)


def main():
    blob = TFLITE.read_bytes()
    sha = hashlib.sha256(blob).hexdigest()
    if sha != EXPECT_SHA:
        raise SystemExit("STOP: model SHA256 mismatch")
    it = tf.lite.Interpreter(model_path=str(TFLITE))
    it.allocate_tensors()
    inp, out = it.get_input_details()[0], it.get_output_details()[0]

    print("=" * 74)
    print("ON-DEVICE SELF-TEST VECTOR GENERATION")
    print("=" * 74)
    print(f"  model sha256 : {sha} (verified)")

    vectors = []

    # ---- Vector A: LCG -------------------------------------------------------
    pcm_a = lcg_pcm()
    print(f"\n  [A] lcg     : seed=0x{LCG_SEED:08X} a={LCG_A} c={LCG_C}")
    print(f"      pcm[0..4] = {list(pcm_a[:5])}")
    print(f"      pcm min/max = {pcm_a.min()} / {pcm_a.max()}")
    vectors.append(("lcg", pcm_a, False))

    # ---- Vector B: one real window ------------------------------------------
    import soundfile as sf
    wavs = sorted(p for p in WAV_DIR.rglob("*.wav"))
    pcm_b = None
    if wavs:
        p = wavs[0]
        a, sr = sf.read(str(p), dtype="int16", always_2d=False)
        if a.ndim > 1:
            a = a[:, 0]
        a = a[:N] if len(a) >= N else np.pad(a, (0, N - len(a)))
        pcm_b = a.astype(np.int16)
        print(f"\n  [B] speech  : {p.name}  (read-only, first {N} samples)")
        vectors.append(("speech", pcm_b, True))

    results = []
    for name, pcm, store in vectors:
        q_feat = py_features_int8(pcm)
        it.set_tensor(inp["index"], q_feat.reshape(1, FRAMES, BINS, 1))
        it.invoke()
        q_out = int(it.get_tensor(out["index"])[0, 0])
        det = q_out >= Q_MIN
        score = (q_out - out["quantization"][1]) * out["quantization"][0]
        print(f"      -> q_out = {q_out}   score = {score:.6f}   detected = {det}")
        results.append((name, pcm, q_feat, q_out, det, store))

    # ---- emit ---------------------------------------------------------------
    ts = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    h = [
        "// Auto-generated by tools/gen_selftest_vectors.py -- DO NOT EDIT BY HAND.",
        "//",
        "// Expected on-device self-test results, computed with the desktop",
        "// TensorFlow reference frontend and the frozen V2.3 INT8 model.",
        f"//   model sha256 : {sha}",
        f"//   generated    : {ts}",
        "",
        "#ifndef IRA_SELFTEST_DATA_H_",
        "#define IRA_SELFTEST_DATA_H_",
        "",
        "#include <stdint.h>",
        "",
        "#ifdef __cplusplus",
        'extern "C" {',
        "#endif",
        "",
        "#define IRA_SELFTEST_SAMPLES 16000",
        "#define IRA_SELFTEST_FEATURES 1960  // 49 * 40",
        "",
        "// Deterministic LCG used by vector A. Mirrors the Python generator:",
        f"//   state = state * {LCG_A} + {LCG_C}   (uint32 wraparound)",
        "//   sample = (int16_t)((state >> 16) & 0xFFFF)",
        f"#define IRA_SELFTEST_LCG_SEED 0x{LCG_SEED:08X}u",
        f"#define IRA_SELFTEST_LCG_A {LCG_A}u",
        f"#define IRA_SELFTEST_LCG_C {LCG_C}u",
        "",
        "// Fills pcm[] with vector A. No waveform is stored in flash.",
        "void ira_selftest_fill_lcg(int16_t pcm[IRA_SELFTEST_SAMPLES]);",
        "",
    ]
    cc = [
        "// Auto-generated by tools/gen_selftest_vectors.py -- DO NOT EDIT BY HAND.",
        f"//   model sha256 : {sha}",
        f"//   generated    : {ts}",
        "",
        '#include "ira_selftest_data.h"',
        "",
        "void ira_selftest_fill_lcg(int16_t pcm[IRA_SELFTEST_SAMPLES]) {",
        "  uint32_t s = IRA_SELFTEST_LCG_SEED;",
        "  for (int i = 0; i < IRA_SELFTEST_SAMPLES; ++i) {",
        "    s = (uint32_t)(s * IRA_SELFTEST_LCG_A + IRA_SELFTEST_LCG_C);",
        "    pcm[i] = (int16_t)(uint16_t)((s >> 16) & 0xFFFFu);",
        "  }",
        "}",
        "",
    ]

    for name, pcm, q_feat, q_out, det, store in results:
        U = name.upper()
        h += [
            f"// ---- vector '{name}' ----",
            f"extern const int8_t ira_selftest_{name}_features[IRA_SELFTEST_FEATURES];",
            f"#define IRA_SELFTEST_{U}_Q_OUT ({q_out})",
            f"#define IRA_SELFTEST_{U}_DETECTED {1 if det else 0}",
            "",
        ]
        flat = q_feat.reshape(-1)
        cc.append(f"const int8_t ira_selftest_{name}_features[IRA_SELFTEST_FEATURES] = {{")
        for i in range(0, len(flat), 16):
            cc.append("    " + " ".join(f"{int(v)}," for v in flat[i:i + 16]))
        cc += ["};", ""]
        if store:
            h += [
                f"extern const int16_t ira_selftest_{name}_pcm[IRA_SELFTEST_SAMPLES];",
                "",
            ]
            cc.append(f"const int16_t ira_selftest_{name}_pcm[IRA_SELFTEST_SAMPLES] = {{")
            for i in range(0, len(pcm), 16):
                cc.append("    " + " ".join(f"{int(v)}," for v in pcm[i:i + 16]))
            cc += ["};", ""]

    h += ["#ifdef __cplusplus", "}  // extern \"C\"", "#endif", "",
          "#endif  // IRA_SELFTEST_DATA_H_", ""]

    OUT_H.write_text("\n".join(h), encoding="utf-8")
    OUT_CC.write_text("\n".join(cc), encoding="utf-8")
    print(f"\n  wrote {OUT_H} ({OUT_H.stat().st_size} bytes)")
    print(f"  wrote {OUT_CC} ({OUT_CC.stat().st_size} bytes)")
    print("\n  Expected values are now frozen into the firmware self-test.")


if __name__ == "__main__":
    main()
